# Generated by Django 4.2 on 2023-04-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        default="default_profile.png", upload_to="profile_photos"
                    ),
                ),
                ("linked_in", models.TextField(blank=True, default="")),
                ("github", models.TextField(blank=True, default="")),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={"ordering": ["position", "name"],},
        ),
        migrations.CreateModel(
            name="Team_Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Team_Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(default="", max_length=50)),
                ("slug", models.SlugField(blank=True, default="")),
                ("members", models.ManyToManyField(blank=True, to="example.member")),
                (
                    "team",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="example.team_name",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="team_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="example.team_name"
            ),
        ),
    ]
